### ISSUE TITLE
Documentation anywhere?

### ISSUE THREAD

**Issue by KarlZeilhofer** [RevolutionPi/piControl#1]
Hi, 

I'm really impressed by the open nature of this project "RevolutionPi"

You are also providing a Maker-Set in a DIN-rail housing in your web shop. To make this really useful, one has to understand the communication protocol on the PiBridge. 

Do you have any kind of documentation for this kernel-module? There are many abbrevations, which one only can guess, what they mean. 

Especially interesting would be some hints, where to implement a new module type, and if this source code can also be used on the module-side for its microcontrollers firmware. 

Big Thumbs Up and kind regards from Austria, 
Karl

**Comment by mduckeck** [comment]
Hi Karl,
we are very busy at the moment because of a new jessie release for the RevPi and the fair in nuremberg. Therefore we did not provide the source code yet.
We plan to provide the source code of the RevPi DIO module including some documentation, but we will need some weeks to do that.
king regards
Mathias

**Comment by KarlZeilhofer** [comment]
wow, great to here!
greets, Karl
